version = 0.1
[default.deploy.parameters]
stack_name = "lambda-barcode-api"
resolve_s3 = true
s3_prefix = "lambda-barcode-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []
